### ISSUE TITLE
Better error message if key doesn't exist due to wrong species config

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/bionty#492]
It was impossible to figure out what's going on for me with the "KeyError" that's thrown when setting species to "human":

<img width="566" alt="image" src="https://github.com/laminlabs/bionty/assets/16916678/fe5624d7-bfb8-450f-8df0-48059a6158bd">

Things are worse when used within lamindb because of how the error propagates.

**Comment by falexwolf** [comment]
There was a typo above. I meant "yeast"!

**Comment by falexwolf** [comment]
The behavior seems to have changed:
<img width="336" alt="image" src="https://github.com/laminlabs/bionty/assets/16916678/7c0af99a-3e35-4636-bc71-cbde7c6f326f">

**Comment by falexwolf** [comment]
Updated the issue! Sorry, @Zethson, I had pasted an example where things worked rather than one where things didn't work.

**Comment by Zethson** [comment]
```
>>> import lnschema_bionty as lb
>>> lb.settings.species = "yeast"
✅ loaded instance: testuser1/nextflow-bulkrna (lamindb 0.51a1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeth/miniconda3/envs/lamindb/lib/python3.10/site-packages/lnschema_bionty/__init__.py", line 59, in __getattr__
    return globals()[name]
KeyError: 'settings'
```
